spring:
  # PostgreSQL DB 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: manseok
    password: manseok

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create

  mvc:
    view:
      suffix: .html
      prefix: /resources/templates/